app:
  datasource:
    main:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always